pipeline:
  identify:
    image: docker
    commands:
      # Grab the current version, prevents race conditions
      - apk add --no-cache curl jq
      # Hugbug, you really gotta fix this bro :(
      - set -o pipefail
      - curl -fL "https://api.github.com/repos/nzbget/nzbget/releases/latest" > .nzbget_latest_release
      - jq -r '.tag_name' .nzbget_latest_release > .nzbget_stable_tag
      - jq -r '.name' .nzbget_latest_release > .nzbget_stable_name

  build:
    image: docker
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - apk add --no-cache jq
      - docker build --no-cache --pull --build-arg NZBGET_TAG=$(cat .nzbget_stable_tag) -t nzbget-dev .

  test:
    image: docker
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - apk add --no-cache curl
      - CON_NAME=$(docker run -d --user=root nzbget-dev) # Need root for config
      - timeout -t 10 docker logs $$CON_NAME &
      - sleep 5
      - IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $$CON_NAME)
      - if [ -z "$IP" ]; then
            echo "The container exited.. sadpanda";
            docker inspect --format='{{.State.ExitCode}}' $$CON_NAME;
            docker rm $$CON_NAME
            exit 25;
        fi
      - curl -sSLu nzbget:tegbzn6789 --max-time 3 --retry 5 --retry-delay 2 --retry-connrefused $IP:6789 > /dev/null
      - docker kill $$CON_NAME # Not really needed, but keeps things quick
      - docker rm $$CON_NAME

  publish:
    image: docker
    secrets: [ docker_user, docker_user ]
    when:
       event: [push, tag, deployment]
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    commands:
       - echo $docker_user
       - docker tag nzbget-dev spritsail/nzbget:latest
       - docker tag nzbget-dev spritsail/nzbget:$(cat .nzbget_stable_name)
       - docker login -u $docker_user -p $docker_pass
       - docker push spritsail/nzbget
       - docker rmi nzbget-dev spritsail/nzbget:latest spritsail/nzbget:$(cat .nzbget_stable_name)
       - echo "CONGRATS! SUCCESSFULLY BUILT NZBGET-STABLE!"

  notify:
    image: appleboy/drone-telegram
    when: { status: [ success, failure ] }
    secrets: [ telegram_token, telegram_to ]
    message: |
      *{{repo.owner}}/{{repo.name}} [{{commit.branch}}]*: Build #{{build.number}}: *{{uppercase build.status}}*
      {{build.link}}
