pipeline:
  identify:
    image: docker
    commands:
      - set -o pipefail
      - apk add --no-cache git
      - dir="$(mktemp -d)"
      - git clone https://github.com/nzbget/nzbget.git "$dir"
      - git -C "$dir" rev-parse --verify HEAD | tee .nzbget_dev_head
      - ( echo -n 'dev-r'; git -C "$dir" rev-list HEAD | wc -l; ) | tee .nzbget_dev_tag

  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: nzbget-dev
    build_args:
      - 'NZBGET_VER=%file: .nzbget_dev_tag'
      - 'NZBGET_TAG=%file: .nzbget_dev_head'

  test:
    image: docker
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    commands:
      - apk add --no-cache curl
      - CON_NAME=$(docker run -d nzbget-dev)
      - timeout -t 10 docker logs -f $$CON_NAME &
      - sleep 5
      - IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $$CON_NAME)
      - if [ -z "$IP" ]; then
            echo "The container exited.. sadpanda";
            docker inspect --format='{{.State.ExitCode}}' $$CON_NAME;
            docker rm $$CON_NAME
            exit 25;
        fi
      - curl -sSLu nzbget:tegbzn6789 --max-time 3 --retry 5 --retry-delay 2 --retry-connrefused $IP:6789 > /dev/null
      - docker kill $$CON_NAME # Not really needed, but keeps things quick
      - docker rm $$CON_NAME

  publish:
    image: spritsail/docker-publish
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    when: { branch: [ develop ], event: [ push, tag, deployment ] }
    from: nzbget-dev
    repo: spritsail/nzbget
    tags:
      - 'dev'
      - '%file: .nzbget_dev_tag'

  notify:
    image: appleboy/drone-telegram
    when: { status: [ success, failure ] }
    secrets: [ telegram_token, telegram_to ]
    message: |
      *{{repo.owner}}/{{repo.name}} [{{commit.branch}}]*: Build #{{build.number}}: *{{uppercase build.status}}*
      {{build.link}}
