pipeline:
  identify:
    image: docker
    commands:
      # Grab the current version, prevents race conditions
      - apk add --no-cache curl jq
      # Hugbug, you really gotta fix this bro :(
      - set -o pipefail
      - curl -fL "https://api.github.com/repos/nzbget/nzbget/releases/latest" > .nzbget_latest_release
      - jq -r '.tag_name' .nzbget_latest_release > .nzbget_stable_tag
      - jq -r '.name' .nzbget_latest_release > .nzbget_stable_name

  build:
    image: docker
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - apk add --no-cache jq
      - docker build --no-cache --pull --build-arg NZBGET_TAG=$(cat .nzbget_stable_tag) -t nzbget-dev .

  test:
    image: docker
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - apk add --no-cache curl
      - CON_NAME=$(docker run -d --user=root nzbget-dev) # Need root for config
      - sleep 5  # Wait for NzbGet to start!
      - docker logs $$CON_NAME
      - IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $$CON_NAME)
      - if [ -z "$IP" ]; then
            echo "The container exited.. sadpanda";
            docker inspect --format='{{.State.ExitCode}}' $$CON_NAME;
            exit 25;
        fi
      - curl -sSLu nzbget:tegbzn6789 --max-time 3 --retry 5 --retry-delay 5 $IP:6789 > /dev/null
      - docker kill $$CON_NAME # Not really needed, but keeps things quick
      - docker rm $$CON_NAME

  publish:
    image: docker
    secrets: [ DOCKER_USER, DOCKER_PASS ]
    when:
       event: [push, tag, deployment]
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    commands:
       - echo $DOCKER_USER
       - docker tag nzbget-dev adamant/nzbget:latest
       - docker tag nzbget-dev adamant/nzbget:$(cat .nzbget_stable_name)
       - docker login -u $DOCKER_USER -p $DOCKER_PASS
       - docker push adamant/nzbget
       - docker rmi nzbget-dev adamant/nzbget:latest adamant/nzbget:$(cat .nzbget_stable_name)
       - echo "CONGRATS! SUCCESSFULLY BUILT NZBGET-STABLE!"
